# frozen_string_literal: true

require_relative "harness/errors"
require_relative "harness/event"
require_relative "harness/agent_profile"
require_relative "harness/token_estimator"
require_relative "harness/checkpoint"
require_relative "harness/command"
require_relative "harness/hooks"
require_relative "harness/middleware"
require_relative "harness/context/fragment"
require_relative "harness/context/provider"
require_relative "harness/context/builder"
require_relative "harness/context/providers/request"
require_relative "harness/context/providers/prompt"
require_relative "harness/context/providers/skill"
require_relative "harness/context/providers/tool_search"
require_relative "harness/context/providers/memory"
require_relative "harness/context/providers/session"
require_relative "harness/policy/policy"
require_relative "harness/policy/engine"
require_relative "harness/registry"
require_relative "harness/tool_registry"
require_relative "harness/workflow_registry"
require_relative "harness/policy_registry"
require_relative "harness/capability_registry"
require_relative "harness/prompt_catalog"
require_relative "harness/plugin"
require_relative "harness/plugin/loader"
require_relative "harness/store"
require_relative "harness/stores/memory"
require_relative "harness/stores/sqlite"
require_relative "harness/session_store"
require_relative "harness/task_store"
require_relative "harness/checkpoint_store"
require_relative "harness/pending_action_store"
require_relative "harness/memory_store"
require_relative "harness/recovery"
require_relative "harness/command_bus"
require_relative "harness/commands/create_session"
require_relative "harness/commands/cancel_task"
require_relative "harness/commands/pause_task"
require_relative "harness/commands/approve_action"
require_relative "harness/commands/send_message"
require_relative "harness/commands/resume_task"
require_relative "harness/commands/trigger_workflow"
require_relative "harness/event_stream"
require_relative "harness/task_actor"
require_relative "harness/session_actor"
require_relative "harness/skill_catalog"
require_relative "harness/tool_catalog"
require_relative "harness/turn_state"
require_relative "harness/capability/resolved_tool"
require_relative "harness/tool_envelope"
require_relative "harness/executor"
# NÃO requerer "harness/tools/load_skill" aqui: ele faz `require "ruby_llm"` no
# topo (herda de RubyLLM::Tool) e puxaria a gem em load-time. O Executor o
# carrega lazy dentro de create_chat (D9).

module Harness
end
