# frozen_string_literal: true

require_relative "harness/errors"
require_relative "harness/coercion"
require_relative "harness/env_schema"
require_relative "harness/allowlist"
require_relative "harness/event"
require_relative "harness/agent_profile"
require_relative "harness/subagent_graph"
require_relative "harness/model_policy"
require_relative "harness/model_selection"
require_relative "harness/model_resolver"
require_relative "harness/tool_definition"
require_relative "harness/tool_manifest"
require_relative "harness/frontmatter"
require_relative "harness/token_estimator"
require_relative "harness/checkpoint"
require_relative "harness/command"
require_relative "harness/hooks"
require_relative "harness/middleware"
# Production edge (item 33 / §12 G7): windowed counters + the rate-limit/cost
# Middleware. Both inert until configured (nil/0 = off).
require_relative "harness/usage_ledger"
require_relative "harness/edge_limiter"
# Content safety / guardrails (RFC-0009). detectors.rb is self-contained (the eval
# requires it directly, D4); the rest hang off Middleware/hooks seams. No ruby_llm
# at load-time — Factory requires the gem lazily, like the Executor's create_chat.
require_relative "harness/safety/detectors"
require_relative "harness/safety/safe_responses"
require_relative "harness/safety/config"
require_relative "harness/safety/moderator"
require_relative "harness/safety/output_filter"
require_relative "harness/safety/input_guardrail"
require_relative "harness/safety/output_validator"
require_relative "harness/safety/factory"
require_relative "harness/context/fragment"
require_relative "harness/context/priority"
require_relative "harness/context/provider"
require_relative "harness/context/catalog_provider"
require_relative "harness/context/builder"
require_relative "harness/context/providers/request"
require_relative "harness/context/providers/prompt"
require_relative "harness/context/providers/skill"
require_relative "harness/context/providers/tool_search"
require_relative "harness/context/providers/memory"
require_relative "harness/context/providers/session"
require_relative "harness/policy/policy"
require_relative "harness/policy/engine"
require_relative "harness/registry"
require_relative "harness/tool_registry"
require_relative "harness/workflow"
require_relative "harness/workflow_registry"
require_relative "harness/policy_registry"
require_relative "harness/capability_registry"
require_relative "harness/prompt_catalog"
require_relative "harness/plugin"
require_relative "harness/plugin/loader"
require_relative "harness/store"
require_relative "harness/stores/memory"
require_relative "harness/stores/sqlite"
require_relative "harness/session_store"
require_relative "harness/task_store"
require_relative "harness/checkpoint_store"
require_relative "harness/pending_action_store"
require_relative "harness/delegation_store"
require_relative "harness/memory_store"
require_relative "harness/config_store"
require_relative "harness/profile_source"
require_relative "harness/agent_file_store"
require_relative "harness/skill_store"
require_relative "harness/secret_masking"
require_relative "harness/tool_store"
require_relative "harness/tool_trace_store"
require_relative "harness/egress_guard"
require_relative "harness/sandbox"
require_relative "harness/http_client"
require_relative "harness/overlay_tool_registry"
require_relative "harness/settings_store"
require_relative "harness/llm_provider_store"
require_relative "harness/llm_configurator"
# LLM-first onboarding surface (item 20 / §5.6): serves start.md + models.json + the
# public docs. Reads the settings/provider stores above at call-time (order is free).
require_relative "harness/onboarding"
require_relative "harness/mcp_store"
require_relative "harness/mcp_http_client"
require_relative "harness/mcp_tool_ingestor"
require_relative "harness/system_file_store"
require_relative "harness/recovery"
require_relative "harness/command_bus"
require_relative "harness/commands/create_session"
require_relative "harness/commands/cancel_task"
require_relative "harness/commands/pause_task"
require_relative "harness/commands/approve_action"
require_relative "harness/commands/send_message"
require_relative "harness/commands/resume_task"
require_relative "harness/commands/trigger_workflow"
require_relative "harness/commands/agent_payload"
require_relative "harness/commands/create_agent"
require_relative "harness/commands/update_agent"
require_relative "harness/commands/delete_agent"
require_relative "harness/commands/set_agent_tools"
require_relative "harness/commands/write_agent_file"
require_relative "harness/commands/delete_agent_file"
require_relative "harness/commands/restore_agent_file"
require_relative "harness/commands/write_skill"
require_relative "harness/commands/set_skill_agents"
require_relative "harness/commands/memory_put_fact"
require_relative "harness/commands/memory_forget_fact"
require_relative "harness/commands/memory_add_note"
require_relative "harness/commands/update_settings"
require_relative "harness/commands/upsert_llm_provider"
require_relative "harness/commands/delete_llm_provider"
require_relative "harness/commands/upsert_mcp"
require_relative "harness/commands/delete_mcp"
require_relative "harness/commands/write_system_file"
require_relative "harness/commands/delete_system_file"
require_relative "harness/commands/restore_system_file"
require_relative "harness/commands/write_data_tool"
require_relative "harness/commands/delete_data_tool"
require_relative "harness/commands/restore_data_tool"
require_relative "harness/commands/import_tools"
require_relative "harness/commands/import_mcp_tools"
require_relative "harness/event_stream"
require_relative "harness/task_actor"
require_relative "harness/session_actor"
require_relative "harness/skill_catalog"
require_relative "harness/tool_catalog"
require_relative "harness/turn_state"
require_relative "harness/turn_timing"
require_relative "harness/capability/resolved_tool"
require_relative "harness/tool_envelope"
require_relative "harness/tool_assembly"
require_relative "harness/chat_builder"
require_relative "harness/executor"
require_relative "harness/pack"
require_relative "harness/pack_importer"
require_relative "harness/telemetry"
# Strict config + diagnosis (item 23 / §8.1). Doctor reads the config stores above;
# EnvSchema (required at the top) is its env layer.
require_relative "harness/doctor"
# Shared composition core for both roots (config/wiring.rb + config/deployment.rb).
# Only references the classes above at call-time, so require order is unconstrained.
require_relative "harness/wiring/graph"
# Public Ruby DSL (item 36): Harness.agent { … }. The Builder is gem-free (it only
# generates a Pack); the runtime (chat/serve) is required lazily by Definition, so
# `require "harness"` stays free of ruby_llm and the HTTP server.
require_relative "harness/dsl"
# Do NOT require "harness/tools/load_skill" here: it does `require "ruby_llm"` at
# the top (inherits from RubyLLM::Tool) and would pull the gem in at load-time. The
# Executor loads it lazily inside create_chat (D9).

module Harness
  VERSION = "0.1.0"
end
